development:
  clients:
    default:
      database: farmbot_web_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: farmbot_web_test
      hosts:
        - <%= ENV['MONGO_HOST'] || 'localhost:27017' %>
      options:
        # read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        # max_retries: 1
        # retry_interval: 0
production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
staging:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
